//go:build ignore

// Generates a Go source file with an embedded GTFOBins lookup map.
// Usage: go run tools/generate_lookup.go > internal/policy/gtfobins_data.go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

type Binary struct {
	Name         string   `json:"name"`
	Functions    []string `json:"functions"`
	RiskLevel    string   `json:"risk_level"`
	ShellEscape  bool     `json:"shell_escape"`
	ReverseShell bool     `json:"reverse_shell"`
	FileRead     bool     `json:"file_read"`
	FileWrite    bool     `json:"file_write"`
	Download     bool     `json:"download"`
	Upload       bool     `json:"upload"`
}

type DB struct {
	Binaries []Binary `json:"binaries"`
}

func main() {
	f, err := os.Open("gtfobins/gtfobins.json")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	var db DB
	if err := json.NewDecoder(f).Decode(&db); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	sort.Slice(db.Binaries, func(i, j int) bool {
		return db.Binaries[i].Name < db.Binaries[j].Name
	})

	fmt.Println(`// Code generated by gtfobins/generate_lookup.go. DO NOT EDIT.`)
	fmt.Println(`// Source: https://gtfobins.org (CC-BY-SA-4.0)`)
	fmt.Println()
	fmt.Println(`package policy`)
	fmt.Println()
	fmt.Println(`// GTFOBinRisk represents the risk level of a binary.`)
	fmt.Println(`type GTFOBinRisk struct {`)
	fmt.Println(`	Level        string   // "critical", "high", "medium", "low"`)
	fmt.Println(`	Capabilities []string // e.g. "shell", "reverse-shell", "file-write"`)
	fmt.Println(`}`)
	fmt.Println()
	fmt.Println(`// GTFOBins maps binary names to their known escape/abuse capabilities.`)
	fmt.Printf("var GTFOBins = map[string]GTFOBinRisk{\n")

	for _, b := range db.Binaries {
		caps := make([]string, len(b.Functions))
		copy(caps, b.Functions)
		sort.Strings(caps)
		quotedCaps := make([]string, len(caps))
		for i, c := range caps {
			quotedCaps[i] = fmt.Sprintf("%q", c)
		}
		fmt.Printf("\t%q: {Level: %q, Capabilities: []string{%s}},\n",
			b.Name, b.RiskLevel, strings.Join(quotedCaps, ", "))
	}

	fmt.Println(`}`)
}
